language: node_js
node_js:
  - 'stable'
  - 'lts/*'

branches:
  only:
  - master
  - develop

before_script:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) download

after_success:
  - npm run .remapcov
  - npx codecov
  - bash <(curl -Ls https://coverage.codacy.com/get.sh)
