name: build

__const__:
  - &node-latest 16.x
  - &node-lts    14.17.x

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: *node-lts
      - run: npm ci
      - run: npm run build
